# Docker file for UMD User Interface
#
FROM aaroc/ansiblecontainer:u1404
MAINTAINER Bruce Becker <bbecker@csir.co.za>
EXPOSE 8888:8888
WORKDIR /root/
RUN ["git","clone","--recursive","https://github.com/AAROC/DevOps.git"]
WORKDIR /root/DevOps/Ansible
RUN ansible-galaxy install -p roles brucellino.Future-Gateway-API-Server
RUN ansible-playbook -c local -i localhost, FutureGatewayAPIServer.yml
CMD rm -rf /root/DevOps
WORKDIR /tmp/apiserver
ENTRYPOINT ["python","fgapiserver.py"]
